[package]
name = "chupkarivy"
version = "2.2.6"
edition = "2021"
rust-version = "1.80.0"

[[bin]]
name = "chupkarivy"
path = "src/main.rs"

[workspace]
members = [
    "chupkarivy_audio",
    "chupkarivy_config",
    "chupkarivy_database",
    "chupkarivy_player",
    "chupkarivy_session",
    "chupkarivy_utils",
    "chupkarivy_stats",
]

[features]
default = ["stats"]
stats = ["chupkarivy_stats"]

[dependencies]
chupkarivy_config = { path = "./chupkarivy_config" }
chupkarivy_database = { path = "./chupkarivy_database" }
chupkarivy_player = { path = "./chupkarivy_player" }
chupkarivy_session = { path = "./chupkarivy_session" }
chupkarivy_utils = { path = "./chupkarivy_utils" }
chupkarivy_stats = { path = "./chupkarivy_stats", optional = true }

librespot = { git = "https://github.com/librespot-org/librespot.git", tag = "v0.5.0", default-features = false }
anyhow = "1.0.93"
dotenvy = "0.15.7"
env_logger = "0.11.5"
log = "0.4.22"
poise = "0.6.1"
serenity = "0.12.2"
songbird = { version = "0.4.4", features = ["simd-json"] }
tokio = { version = "1.41.1", features = ["full"] }
rustls = { version = "0.23.16", features = ["ring"] }

[profile.release]
opt-level = 3
lto = true
strip = true

[workspace.package]
version = "2.2.6"
